name: Fetch Trends

on:
  schedule:
    - cron: "11 * * * *"   # hourly
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests feedparser

      - name: Build data/trends.json
        env:
          YT_API_KEY: ${{ secrets.YT_API_KEY }}   # optional
        run: |
          mkdir -p data
          python scripts/fetch_trends.py

      - name: Commit changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/trends.json
            git commit -m "chore: update trends.json [skip ci]"
            git push
          fi
